version: '3'
services:
  rabbitmq:
    container_name: rabbitmq1
    image: rabbitmq:3.6-management   
    ports:
      - "15674:15672"        
#   environment: 
#     RABBITMQ_DEFAULT_PASS: pass
#     RABBITMQ_DEFAULT_USER: user
#     RABBITMQ_DEFAULT_VHOST: vhost
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro    
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro    
  mssql:
    container_name: mssql-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_DB: dev
      SA_PASSWORD: "Password1!"
      ACCEPT_EULA: "Y"
      MSSQL_USER: elman
      MSSQL_PASSWORD: Password1!
    volumes:
      - ./mssql/setup.sql:/etc/mssql/setup.sql:ro
      - ./mssql/entrypoint.sh:/etc/mssql/entrypoint.sh:ro
      - ./mssql/configure-db.sh:/etc/mssql/configure-db.sh:ro
    entrypoint: [bash, /etc/mssql/entrypoint.sh]

  ibmmq:
    container_name: ibmmq-base
    image: ibmcom/mq
    ports:
      - "1414:1414"
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QMGRBASE"
    volumes:
      - ./ibmmq/config.mqsc:/etc/mqm/config.mqsc:ro  